"""empty message

Revision ID: 74d5ce49db24
Revises: bcf0c32cd468
Create Date: 2024-05-20 20:21:08.265798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d5ce49db24'
down_revision = 'bcf0c32cd468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipmento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipamento', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('acessorios', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.Column('fk_nivel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_nivel_id'], ['nivel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipmento')
    # ### end Alembic commands ###
